### ISSUE TITLE
Initialize CLI tool (Create seed data / Deploy to hosting)

### ISSUE THREAD

**Issue by potato4d** [uit-community/nigiyakashi#3]
## Tasks

- [ ] Create firebase configuration automaticity
- [ ] Create seed data
- [ ] Deploy to firebase hosting
